const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const giveHtml = fs.readFileSync("give.html", "utf8");
const scheduleHtml = fs.readFileSync("schedule.html", "utf8");
const resourcesHtml = fs.readFileSync("resources.html", "utf8");
const adminHtml = fs.readFileSync("admin.html", "utf8");
const script = fs.readFileSync("script.js", "utf8");
const adminScript = fs.readFileSync("admin.js", "utf8");
const server = fs.readFileSync("dev-server.js", "utf8");
const vercelConfig = fs.readFileSync("vercel.json", "utf8");

assert.match(html, /id="schedule"/, "Home page should contain minyan times");
assert.match(html, /id="zmanim-list"/, "Home page should contain zmanim");
assert.match(html, /Five Towns Eruv/, "Home page should contain eruv information");
assert.match(html, /id="give"/, "Home page should contain donation information");
assert.match(html, /mailto:ksswoodmere@gmail\.com/, "Home page should include an email link");
assert.match(html, /href="\/resources(?:#|")/, "Home page should link to resources page with a clean URL");
assert.doesNotMatch(resourcesHtml, /id="give"/, "Resources page should not duplicate donation information");
assert.doesNotMatch(resourcesHtml, /Five Towns Eruv Map/, "Resources page should not duplicate eruv information");
assert.ok(html.indexOf('class="hero"') < html.indexOf('class="status-strip"'), "Home page should match the bulletin-style hero before practical info");
assert.ok(html.indexOf('class="status-strip"') < html.indexOf('id="schedule"'), "Home page should show minyan schedule under next minyan");
assert.ok(html.indexOf('id="schedule"') < html.indexOf('class="home-link-strip"'), "Home page should show donate, eruv, and email after the schedule");
assert.ok(html.indexOf("<span>Next Minyan</span>") < html.indexOf("<span>Address</span>"), "Home page should show next minyan above address");
assert.match(html, /<header class="site-header">/, "Home page should include the site header");
assert.match(html, /<a href="#schedule">Minyanim<\/a>\s*<a href="\/resources#community">Visitor Info<\/a>\s*<a class="nav-support" href="\/give">Support Us<\/a>/, "Home header should use the shared compact nav");
assert.match(resourcesHtml, /<a href="\/#schedule">Minyanim<\/a>\s*<a href="#community">Visitor Info<\/a>\s*<a class="nav-support" href="\/give">Support Us<\/a>/, "Resources header should use the shared compact nav");
assert.match(scheduleHtml, /<a href="\/#schedule" aria-current="page">Minyanim<\/a>\s*<a href="\/resources#community">Visitor Info<\/a>\s*<a class="nav-support" href="\/give">Support Us<\/a>/, "Schedule header should use the shared compact nav");
assert.match(giveHtml, /<a href="\/#schedule">Minyanim<\/a>\s*<a href="\/resources#community">Visitor Info<\/a>\s*<a class="nav-support" href="\/give" aria-current="page">Support Us<\/a>/, "Give header should use the shared compact nav");
assert.doesNotMatch(html, /resources\.html#learning/, "Home header should not expose every resource section as a separate link");
assert.doesNotMatch(html, /resources\.html#visit/, "Home header should not expose visit as a separate link");
assert.doesNotMatch(html, />Donate<\/a>/, "Home header should say Support Us, not Donate");
assert.doesNotMatch(html, />More<\/a>/, "Home header should not use More as a vague link");
assert.doesNotMatch(html, /class="thumb-nav"/, "Home page should not include bottom navigation");
assert.doesNotMatch(resourcesHtml, /class="thumb-nav"/, "Resources page should not include bottom navigation buttons");
assert.doesNotMatch(scheduleHtml, /class="thumb-nav"/, "Schedule page should not include bottom navigation buttons");
assert.doesNotMatch(html, /class="hero-actions"/, "Home hero should not include extra CTA buttons");
assert.doesNotMatch(html, />Minyan Times</, "Home hero should not duplicate the schedule with a button");
assert.match(scheduleHtml, /id="schedule"/, "Schedule page should contain the schedule section");
assert.match(giveHtml, /id="give"/, "Give page should contain Zelle support section");
assert.match(giveHtml, /body class="give-page"/, "Give page should use give-specific layout tuning");
assert.match(giveHtml, /Sponsor &amp; Dedicate/, "Give page should contain sponsor and dedication content");
assert.match(giveHtml, /class="copy-button"[^>]*data-copy="ksswoodmere@gmail\.com"/, "Give page should include a Zelle copy button");
assert.doesNotMatch(resourcesHtml, /Sponsor &amp; Dedicate/, "Resources page should not duplicate give content");
assert.match(resourcesHtml, /id="resources"/, "Resources page should contain local resources");
assert.match(resourcesHtml, /id="learning"/, "Resources page should contain learning content");
assert.match(html, /id="announcements"[^>]*hidden/, "Announcements section should start hidden");
assert.match(html, /class="announcement-banner"/, "Announcements should render as a top banner");
assert.match(html, /id="announcement-list"/, "Announcement list should be present");
assert.match(html, /class="site-footer"/, "Public page should include a footer");
assert.match(html, /aria-label="Footer navigation"/, "Footer should include quick navigation");
assert.match(html, /href="\/admin">Staff<\/a>/, "Footer should link to the clean admin URL with staff copy");
assert.match(html, /href="\/resources#community">Visitor Info<\/a>/, "Home footer should include visitor info");
assert.match(html, /href="\/give">Support Us<\/a>/, "Home footer should link to the give page");
assert.match(resourcesHtml, /href="\/resources#community">Visitor Info<\/a>/, "Resources footer should match the shared footer links");
assert.match(scheduleHtml, /href="\/resources#community">Visitor Info<\/a>/, "Schedule footer should match the shared footer links");
assert.match(giveHtml, /href="\/resources#community">Visitor Info<\/a>/, "Give footer should match the shared footer links");
assert.match(html, /class="footer-bottom compact-footer"/, "Home footer should use the compact footer");
assert.match(giveHtml, /class="footer-bottom compact-footer"/, "Give footer should use the compact footer");
assert.match(resourcesHtml, /class="footer-bottom compact-footer"/, "Resources footer should use the compact footer");
assert.match(scheduleHtml, /class="footer-bottom compact-footer"/, "Schedule footer should use the compact footer");
assert.doesNotMatch(`${html}\n${giveHtml}\n${resourcesHtml}\n${scheduleHtml}`, /<div class="footer-grid">/, "Public footers should not duplicate address and contact info");
assert.doesNotMatch(`${html}\n${giveHtml}\n${resourcesHtml}\n${scheduleHtml}`, /<div class="footer-bottom compact-footer">(?:(?!<\/div>)[\s\S])*<strong>ksswoodmere@gmail\.com<\/strong>/, "Public footer bottom should not repeat the email address");
assert.doesNotMatch(`${html}\n${giveHtml}\n${resourcesHtml}\n${scheduleHtml}`, />Staff Sign In<\/a>/, "Public footer should shorten staff link copy");
assert.doesNotMatch(`${html}\n${giveHtml}\n${resourcesHtml}\n${scheduleHtml}`, /href="(?:index|resources|schedule|give)\.html/, "Public links should use clean URLs instead of .html files");

["weekday-shacharit", "sunday-shacharit", "daily-mincha-arvit"].forEach((key) => {
  assert.match(`${html}\n${scheduleHtml}`, new RegExp(`data-schedule-key="${key}"`), `${key} should be rendered in markup`);
  assert.match(script, new RegExp(key), `${key} should be handled by script`);
});

["regular", "shabbat", "zmanim"].forEach((tab) => {
  assert.match(scheduleHtml, new RegExp(`data-tab="${tab}"`), `${tab} tab should be present`);
  assert.match(scheduleHtml, new RegExp(`data-panel="${tab}"`), `${tab} panel should be present`);
});

assert.match(script, /\/api\/updates/, "Public page should fetch board updates");
assert.match(script, /function renderAnnouncements/, "Public page should render announcements");
assert.match(script, /function applyBoardUpdates/, "Public page should merge board updates");
assert.match(script, /function fallbackCopyText/, "Copy button should have a clipboard fallback");
assert.doesNotMatch(script, /Copy failed/, "Copy button should not show scary failure text");

assert.match(adminHtml, /Staff Sign In/, "Admin page should present staff sign-in copy");
assert.doesNotMatch(adminHtml, /Board Admin/, "Admin landing page should not use board admin copy");
assert.doesNotMatch(adminHtml, /Update Times and Announcements/, "Admin landing page should keep the sign-in copy minimal");
assert.doesNotMatch(adminHtml, /admin-config-message/, "Admin login should not show helper config copy");
assert.doesNotMatch(adminScript, /shared board password/, "Admin script should not inject shared-password helper copy");
assert.match(adminHtml, /id="admin-login-form"/, "Admin login form should be present");
assert.match(adminHtml, /id="admin-bulletin-form"/, "Admin bulletin upload form should be present");
assert.match(adminHtml, /type="file"/, "Admin upload should use a file input");
assert.match(adminHtml, /accept="application\/pdf,\.pdf"/, "Admin upload should accept PDF files");
assert.match(adminHtml, /id="admin-content-form"/, "Admin editor form should be present");
assert.doesNotMatch(adminHtml, /Latest Shema/, "Admin editor should not expose Latest Shema as a manual board field");
assert.match(adminScript, /\/api\/admin\/login/, "Admin page should log in through backend");
assert.match(adminScript, /\/api\/admin\/bulletin/, "Admin page should upload bulletins through backend");
assert.match(adminScript, /\/api\/admin\/content/, "Admin page should save content through backend");
assert.doesNotMatch(adminScript, /collectSchedule\("latestShema"\)/, "Admin saves should not add manual Latest Shema times");

assert.match(server, /adminApiHandler/, "Dev server should route admin API requests");
assert.match(server, /\/api\/updates/, "Dev server should expose public updates");
assert.match(server, /cleanPageRoutes/, "Dev server should serve clean page routes");
assert.match(server, /legacyPageRoutes/, "Dev server should redirect legacy html page URLs");
assert.match(server, /\["\/index\.html", "\/"\]/, "Dev server should redirect legacy index.html URL");
assert.match(server, /\["\/give", "\/give\.html"\]/, "Dev server should serve clean give route");
assert.match(server, /\["\/give\.html", "\/give"\]/, "Dev server should redirect legacy give.html URL");
assert.match(server, /publicFiles/, "Dev server should restrict static serving to public files");
assert.match(server, /startsWith\("\/assets\/"\)/, "Dev server should only expose the assets directory publicly");
assert.match(server, /redirectHome\(response\)/, "Dev server should redirect private source and data paths");
assert.match(vercelConfig, /"cleanUrls": true/, "Vercel should serve clean extensionless URLs");
assert.match(vercelConfig, /"source": "\/index\.html"/, "Vercel should redirect legacy index.html URL");
assert.match(vercelConfig, /"destination": "\/"/, "Vercel should use / as the home URL");
assert.match(vercelConfig, /"source": "\/admin\.html"/, "Vercel should redirect legacy admin.html URL");
assert.match(vercelConfig, /"destination": "\/admin"/, "Vercel should use /admin as the admin URL");
assert.match(vercelConfig, /"source": "\/give\.html"/, "Vercel should redirect legacy give.html URL");
assert.match(vercelConfig, /"destination": "\/give"/, "Vercel should use /give as the give URL");
assert.match(vercelConfig, /"source": "\/schedule\.html"/, "Vercel should redirect legacy schedule.html URL");
assert.match(vercelConfig, /"destination": "\/schedule"/, "Vercel should use /schedule as the schedule URL");
assert.match(vercelConfig, /"source": "\/resources\.html"/, "Vercel should redirect legacy resources.html URL");
assert.match(vercelConfig, /"destination": "\/resources"/, "Vercel should use /resources as the resources URL");

console.log("UI static test passed.");
